version: '3'
services:
  mongodb:
    image: mongo:3.6
    environment:
    - AUTH=no
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    volumes:
    - ./data/db:/data/db
    ports:
    - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
